trigger:
  branches:
    include:
    - none
variables:
- name: buildConfiguration
  value: 'Release'
- name: solution
  value: '**/*.sln'
- name:  'buildPlatform' 
  value: 'Any CPU'
stages:
- stage: Build
  jobs:
  - job: buildTheApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'NetCore Basic'
        scanPath: '**/*.csproj'
        format: 'HTML'
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
        includePreviewVersions: true # Required for preview versions
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release'
        modifyOutputPath: false
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.zip'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
        ArtifactName: '$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
        publishLocation: 'Container'
    
      