trigger:
  branches:
    include:
    - master
variables:
- name: buildConfiguration
  value: 'Release'

stages:
- stage: Build
  jobs:
  - job: buildTheApp
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
        includePreviewVersions: true # Required for preview versions
      
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        configuration: $(buildConfiguration)
      
    - task: ArchiveFiles@2
      displayName: 'Zipping Generated Artifacts'
      inputs:
          rootFolderOrFile: 
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
          replaceExistingArchive: true
              
    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'io_subscription'
        appType: 'webApp'
        WebAppName: 'netcorepoc'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
