trigger:
  branches:
    include:
    - none
variables:
- name: buildConfiguration
  value: 'Release'
- name: solution
  value: '**/*.sln'
- name:  'buildPlatform' 
  value: 'Any CPU'
stages:
- stage: Build
  jobs:
  - job: buildTheApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
        includePreviewVersions: true # Required for preview versions
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release'
        modifyOutputPath: false
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.zip'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
        flattenFolders: true
    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
    #     artifact: '$(Build.BuildId)'
    #     publishLocation: 'pipeline'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
        ArtifactName: '$(Build.BuildId)'
        publishLocation: 'Container'
    
        
- stage: deploy
  jobs:
  - deployment: VMDeploy
    displayName: deploying onpremise
    pool:
      vmImage: 'windows-latest'
    environment:
     name: '$(Build.SourceBranchName)'
     resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'netcore4'
              WebsitePhysicalPath: 'C:\inetpub\wwwroot\netcore4'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"5004","hostname":"","sslThumbprint":"","sniFlag":false}]}'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'netcore4'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'netcore4'
              Package: '$(Pipeline.Workspace)/$(Build.BuildId)/*.zip'
              TakeAppOfflineFlag: true
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'netcore4'