trigger:
  branches:
    include:
    - none

variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: buildTheApp
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildconfiguration) --output $(System.DefaultWorkingDirectory)/release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--output $(System.DefaultWorkingDirectory)/release'
     
    - task: ArchiveFiles@2
      displayName: 'Zipping Generated Artifacts'
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/release
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
        replaceExistingArchive: true
       
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name) - $(Build.SourceBranchName) - $(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  
- stage: deploy
  jobs:
  - deployment: VMDeploy
    displayName: deploying onpremise
    pool:
      vmImage: 'windows-latest'
    environment:
     name: 'io-iis'
     resourceType: VirtualMachine
     resourceName: kuzko
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/**/*.zip'
              destinationFolder: '$(Pipeline.Workspace)/drop/$(Build.BuildId)'
              cleanDestinationFolder: true
              overwriteExistingFiles: true
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'netcorepoc3'
              WebsitePhysicalPath: 'C:\inetpub\wwwroot\netcorepoc3\'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"5003","hostname":"","sslThumbprint":"","sniFlag":false}]}'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'netcorepoc3'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'netcorepoc3'
              VirtualApplication: 'netcorepoc3'
              Package: '$(Pipeline.Workspace)/drop/$(Build.BuildId)/**/*.zip'
              TakeAppOfflineFlag: true
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'netcorepoc3'










    # - task: AzureRmWebAppDeployment@4
    #   inputs:
    #     ConnectionType: 'AzureRM'
    #     azureSubscription: 'io_subscription'
    #     appType: 'webApp'
    #     WebAppName: 'netcorepoc'
    #     packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'